config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create', as: 'feedback_send'

  resources :badges, only: %i[index] do
    get 'my', on: :collection, to: 'badges#show'
  end

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true

  validate :answers_length

  private

  def answers_length
    errors.add(:answers, "не больше 4") if question.answers.length > 3
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_rewards
  has_many :users, through: :badge_rewards

  validates_presence_of :name, :filename, :rule, :condition

  enum rule: %i[level category first_try]

  def self.filenames
    %w[001-medal   002-trophy     003-flag   004-badge    005-medal
       006-medal   007-star       008-medal  009-trophy   010-flag
       011-trophy  012-medal      013-trophy 014-medal    015-trophy
       016-trophy  017-trophy     018-badge  019-medal    020-badge
       021-badge   022-trophy     023-trophy 024-gift     025-badge
       026-medal   027-badge      028-badge  029-trophy   030-medal
       031-badge   032-medal      033-trophy 034-football 035-diploma
       036-trophy  037-medal      038-trophy 039-trophy   040-trophy
       041-gift    042-trophy     043-badge  044-medal    045-badge
       046-diploma 047-basketball 048-badge  049-medal    050-trophy]
  end

  def count_for(user)
    user.badges.count { |badge| badge == self }
  end
end

app/models/badge_reward.rb
class BadgeReward < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :name, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :email, format: { with: /.+@.+\..+/ }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :github_id, presence: true

  def url
    "https://gist.github.com/#{github_id}"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :test_passages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :completion_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy,   -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard,   -> { where(level: 5..)  }

  scope :by_category, -> category_name do
    joins(:category).where(categories: { name: category_name })
  end

  scope :with_questions, -> do
    joins(:questions).group('tests.id').having('count(questions) > 0')
  end

  def self.titles_by_category(category_name)
    by_category(category_name).order("title DESC").pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  SUCCESSFUL_PERCENT_MARGIN = 85

  def completed?
    current_question.nil?
  end

  def time_out?
    with_time? && completion_time_left.negative?
  end

  def current_question_index
    test.questions.ids.index(current_question.id)
  end

  def success_percent
    percentage = correct_questions / test.questions.size.to_f
    (percentage * 100).to_i
  end

  def successful?
    completed? && success_percent >= SUCCESSFUL_PERCENT_MARGIN
  end

  def with_time?
    test.completion_time.positive?
  end

  def completion_time_left
    seconds = test.completion_time * 60 - (Time.now - created_at)
    seconds.to_i
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  private

  def before_validation_set_current_question
    if self.current_question
      self.current_question = next_question
    else
      self.current_question = test.questions.first if test.present?
    end
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.blank?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :own_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists

  has_many :badge_rewards
  has_many :badges, through: :badge_rewards

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.with_questions
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:title, :level, :category_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to repo.capitalize, "https://github.com/#{author}/#{repo}/"
  end

  def admin?
    current_user.admin? if current_user
  end

  def enum_for_select(model, key)
    model.send(key.to_s.pluralize)
      .map { |value, _| [model.human_enum_name(key, value), value] }
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_header(question)
    if question.new_record?
      'Создание нового вопроса'
    else
      'Редактирование вопроса'
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-text mr-auto">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <%= link_to admin_tests_path do %>
      <%= bootstrap_icon 'hammer', width: 25, height: 25 if admin? %>
    <% end %>
    <%= link_to admin_badges_path do %>
      <%= inline_svg_tag 'badges/008-medal.svg', size: '30px * 30px' %>
    <% end %>
  </span>

  <span class="navbar-text mr-auto text-uppercase font-weight-bold">
    Панель управления TestGuru
  </span>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Добро пожаловать, <b><%= current_user.email %></b>
      <%= link_to 'Выйти', destroy_user_session_path, method: :delete if user_signed_in? %>
    <% end %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/navigation' %>

    <div class="container-fluid px-5 py-2">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

  <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <div class="container-fluid px-5 py-2">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message.html_safe, class: "alert alert-#{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5 px-5">
  <hr>
  <%= github_url('alexamy', 'thinknetica-rails') %>
  <p>Test framework for students and teachers</p>
  <p>alexamy, <%= current_year %></p>
  <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com/' %>
  <br>
  <p>
    Изображения бейджей созданы <%= link_to 'freepik', 'https://www.flaticon.com/authors/freepik' %>
    на сайте <%= link_to 'flaticon', 'https://www.flaticon.com/' %>
  </p>
  <br>
  <%= link_to 'Обратная связь', feedback_path %>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-text mr-auto">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <%= link_to admin_tests_path do %>
      <%= bootstrap_icon 'hammer', width: 25, height: 25 if admin? %>
    <% end %>
    <%= link_to my_badges_path do %>
      <%= inline_svg_tag 'badges/008-medal.svg', size: '30px * 30px' %>
    <% end %>
  </span>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Добро пожаловать, <b><%= current_user.email %></b>
      <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Войти', new_user_session_path %>
      <%= link_to 'Регистрация', new_user_registration_path %>
    <% end %>
  </span>
</nav>