config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create', as: 'feedback_send'

  resources :badges, only: %i[index] do
    get 'my', on: :collection, to: 'badges#show'
  end

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  SUCCESSFUL_PERCENT_MARGIN = 85

  def completed?
    current_question.nil?
  end

  def time_out?
    with_time? && completion_time_left.negative?
  end

  def current_question_index
    test.questions.ids.index(current_question.id)
  end

  def success_percent
    percentage = correct_questions / test.questions.size.to_f
    (percentage * 100).to_i
  end

  def successful?
    completed? && success_percent >= SUCCESSFUL_PERCENT_MARGIN
  end

  def with_time?
    test.completion_time.positive?
  end

  def completion_time_left
    seconds = test.completion_time * 60 - (Time.now - created_at)
    seconds.to_i
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  private

  def before_validation_set_current_question
    if self.current_question
      self.current_question = next_question
    else
      self.current_question = test.questions.first if test.present?
    end
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.blank?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show result update gist]

  def show
  end

  def result
  end

  def gist
    client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
    gist_service = GistQuestionService.new(@test_passage.current_question, client: client)
    response = gist_service.call

    if gist_service.success?
      gist = Gist.create(
        github_id: response[:id],
        question: @test_passage.current_question,
        user: current_user
      )
      flash_options = { notice: t('.success', gist: gist.url) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.time_out?
      send_results_to_email
      BadgeTestReward.call(current_user, @test_passage) if @test_passage.successful?

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def send_results_to_email
    unless @test_passage.completed_at
      @test_passage.touch(:completed_at)
      TestsMailer.completed_test(@test_passage).deliver_now
    end
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def questions_size(test_passage)
    test_passage.test.questions.size
  end

  def success_class(test_passage)
    if test_passage.successful?
      :success
    else
      :fail
    end
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<p><%= t('.complete_percent') %>:
  <span class="<%= success_class(@test_passage) %>">
    <%= @test_passage.success_percent %>%
  </span>
</p>

<%= content_tag :p, @test_passage.successful? ? t('.successful') : t('.failed') %>

<%= link_to t('.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1>
  <%= t('.header') %>
  <%= @test_passage.test.title %>
</h1>

<p>
  <%= t('.question_number') %>
  <%= @test_passage.current_question_index + 1 %> / <%= questions_size(@test_passage) %>

  <% if @test_passage.with_time? %>
    <div class="completion-time">
      <span><%= t('.completion_time') %></span>
      <span class="timer-elapsed" data-start-time="<%= @test_passage.completion_time_left %>">
      </span>
    </div>
  <% end %>

  <div class="progress">
    <%= content_tag :div,
                    '',
                    class: 'progress-bar',
                    role: 'progressbar',
                    data: { progress: @test_passage.current_question_index,
                            total: questions_size(@test_passage) } %>
  </div>
</p>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), method: :put, local: true, id: 'question-form' do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('h.next') %></p>
<% end %>