config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create', as: 'feedback_send'

  resources :badges, only: %i[index] do
    get 'my', on: :collection, to: 'badges#show'
  end

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true

  validate :answers_length

  private

  def answers_length
    errors.add(:answers, "не больше 4") if question.answers.length > 3
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: 'Вопрос создан.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Вопрос обновлен.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Показать', admin_answer_path(answer) %>
  <%= link_to 'Редактировать', edit_admin_answer_path(answer) %>
  <%= link_to 'Удалить',
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: 'Вы уверены?' } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 7, cols: 60, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= form.check_box :correct, class: 'form-check-input' %>
    <%= form.label :correct, class: 'form-check-label' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', admin_answer_path(@answer) %> |
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.header') %></h1>

<p id="notice"><%= notice %></p>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b><%= t('.body') %></b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t('.correct') %></b>
  <%= @answer.correct %>
</p>

<%= link_to t('h.edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('h.back'), admin_question_path(@answer.question) %> |