config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  get 'feedback', to: 'feedback#new'
  post 'feedback', to: 'feedback#create', as: 'feedback_send'

  resources :badges, only: %i[index] do
    get 'my', on: :collection, to: 'badges#show'
  end

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[index]
    resources :badges, except: :show

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_not_found

  def show
  end

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to action: 'show'
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    render plain: "Success"
  end

  private

  def rescue_with_not_found
    render plain: 'Question not found'
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_header(question)
    if question.new_record?
      'Создание нового вопроса'
    else
      'Редактирование вопроса'
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('h.submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'Показать', admin_question_path(question) %></td>
  <td><%= link_to 'Редактировать', edit_admin_question_path(question) %></td>
  <td><%= link_to 'Удалить',
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Вы уверены?'} %></td>
</tr>

app/views/admin/questions/_test_questions.html.erb
<table>
  <tr>
    <th>Вопрос</th>
    <th>Действия</th>
  </tr>
  <%= render partial: 'admin/questions/question', collection: @test.questions %>
</table>

app/views/admin/questions/edit.html.erb
<h1><%= form_header(@question) %></h1>

<%= render 'shared/errors', resource: @question %>
<br>

<%= render 'form' %>

app/views/admin/questions/index.html.erb
<h1>Вопросы</h1>
<%= render 'test_questions' %>

app/views/admin/questions/new.html.erb
<h1><%= form_header(@question) %></h1>

<%= render 'shared/errors', resource: @question %>
<br>

<%= render 'form' %>

app/views/admin/questions/show.html.erb
<p><%= @question.body %></p>

<p>Ответы:</p>

<%= link_to 'Новый ответ', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>
<br>

<%= link_to 'Редактировать', edit_admin_question_path(@question) %>
<%= link_to 'Назад', admin_test_path(@question.test) %>